# Generated by Django 5.2.4 on 2025-07-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='img',
        ),
    ]
