# Generated by Django 5.2.4 on 2025-07-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_rename_image_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descripion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
