# Generated by Django 5.2.4 on 2025-07-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_product_descripion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descripion',
            new_name='description',
        ),
    ]
